name: compresstraj
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - tqdm
  - cudatoolkit
  - scikit-learn
  - pytorch
  - pytorch-lightning
  - mdanalysis
  - natsort
  - python>=3.9
